//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string ID { get; set; }
        public string Nickname { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int Trophies { get; set; }
        public int Michicoins { get; set; }

        public Player() { }
        public Player(string nickname, string password, string name, string lastName, string email)
        {
            this.Nickname = nickname;
            this.Password = password;
            this.Name = name;
            this.LastName = lastName;
            this.Email = email;

        }

        public Player(string id, string nickname, string password, string name, string lastName,
                      string email, int trophies, int michicoins)
        {
            this.ID = id;
            this.Nickname = nickname;
            this.Password = password;
            this.Name = name;
            this.LastName = lastName;
            this.Email = email;
            this.Trophies = trophies;
            this.Michicoins = michicoins;
        }
    }
}
