//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterPage.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegisterPage.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t have account?.
        /// </summary>
        public static string accountQuestion {
            get {
                return ResourceManager.GetString("accountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit?.
        /// </summary>
        public static string confirmationMessage {
            get {
                return ResourceManager.GetString("confirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error with database connection.
        /// </summary>
        public static string connectionErrorMessage {
            get {
                return ResourceManager.GetString("connectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create my account.
        /// </summary>
        public static string createAccountButton {
            get {
                return ResourceManager.GetString("createAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email format.
        /// </summary>
        public static string emailErrorMessage {
            get {
                return ResourceManager.GetString("emailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This mail was sent via RumMichy.
        /// </summary>
        public static string emailMessage {
            get {
                return ResourceManager.GetString("emailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English (en-US).
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish (es-MX).
        /// </summary>
        public static string es_MX {
            get {
                return ResourceManager.GetString("es-MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There’s already a player with that nickname.
        /// </summary>
        public static string existingNicknameMessage {
            get {
                return ResourceManager.GetString("existingNicknameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid nickname and/or password.
        /// </summary>
        public static string failedLogIn {
            get {
                return ResourceManager.GetString("failedLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid confirmation code.
        /// </summary>
        public static string failedVerification {
            get {
                return ResourceManager.GetString("failedVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error with internet connection.
        /// </summary>
        public static string internetConnectionErrorMessage {
            get {
                return ResourceManager.GetString("internetConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid last name format.
        /// </summary>
        public static string lastNameErrorMessage {
            get {
                return ResourceManager.GetString("lastNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid name format.
        /// </summary>
        public static string nameErrorMessage {
            get {
                return ResourceManager.GetString("nameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string nickName {
            get {
                return ResourceManager.GetString("nickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid nickname format.
        /// </summary>
        public static string nickNameErrorMessage {
            get {
                return ResourceManager.GetString("nickNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid password format. The password must have between 8 and 16 characters, at least one digit, at least one lower case, at least one upper case and no whitespace.
        /// </summary>
        public static string passwordErrorMessage {
            get {
                return ResourceManager.GetString("passwordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not Match.
        /// </summary>
        public static string passwordMismatchErrorMessage {
            get {
                return ResourceManager.GetString("passwordMismatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Re-enter Password.
        /// </summary>
        public static string reEnterPassword {
            get {
                return ResourceManager.GetString("reEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Successfully Registered.
        /// </summary>
        public static string registeredAccountMessage {
            get {
                return ResourceManager.GetString("registeredAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string registerLink {
            get {
                return ResourceManager.GetString("registerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a language.
        /// </summary>
        public static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        public static string titleAccount {
            get {
                return ResourceManager.GetString("titleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string titleNew {
            get {
                return ResourceManager.GetString("titleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We send you a message to your email, please write it.
        /// </summary>
        public static string verificationCodeMessage {
            get {
                return ResourceManager.GetString("verificationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your verification code is:.
        /// </summary>
        public static string verificationCodeMessageEmail {
            get {
                return ResourceManager.GetString("verificationCodeMessageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to the RumMichy family.
        /// </summary>
        public static string welcomeMessage {
            get {
                return ResourceManager.GetString("welcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Here goes your code.
        /// </summary>
        public static string yourCodeHere {
            get {
                return ResourceManager.GetString("yourCodeHere", resourceCulture);
            }
        }
    }
}
